export const SUPPORTED_LANGUAGES = [
    { code: "en-US", name: "English (US)", native: "English (US)" },
    { code: "en-GB", name: "English (UK)", native: "English (UK)" },
    { code: "ar-SA", name: "Arabic (Saudi Arabia)", native: "العربية (السعودية)" },
    { code: "ar-EG", name: "Arabic (Egypt)", native: "العربية (مصر)" },
    { code: "es-ES", name: "Spanish (Spain)", native: "Español (España)" },
    { code: "es-MX", name: "Spanish (Mexico)", native: "Español (México)" },
    { code: "fr-FR", name: "French", native: "Français" },
    { code: "de-DE", name: "German", native: "Deutsch" },
    { code: "it-IT", name: "Italian", native: "Italiano" },
    { code: "pt-BR", name: "Portuguese (Brazil)", native: "Português (Brasil)" },
    { code: "pt-PT", name: "Portuguese (Portugal)", native: "Português (Portugal)" },
    { code: "ru-RU", name: "Russian", native: "Русский" },
    { code: "zh-CN", name: "Chinese (Simplified)", native: "简体中文" },
    { code: "zh-TW", name: "Chinese (Traditional)", native: "繁體中文" },
    { code: "ja-JP", name: "Japanese", native: "日本語" },
    { code: "ko-KR", name: "Korean", native: "한국어" },
    { code: "hi-IN", name: "Hindi", native: "हिन्दी" },
    { code: "tr-TR", name: "Turkish", native: "Türkçe" },
    { code: "nl-NL", name: "Dutch", native: "Nederlands" },
    { code: "pl-PL", name: "Polish", native: "Polski" },
    { code: "vi-VN", name: "Vietnamese", native: "Tiếng Việt" },
    { code: "th-TH", name: "Thai", native: "ไทย" },
    { code: "id-ID", name: "Indonesian", native: "Bahasa Indonesia" },
    { code: "ms-MY", name: "Malay", native: "Bahasa Melayu" },
    { code: "fil-PH", name: "Filipino", native: "Filipino" },
    { code: "uk-UA", name: "Ukrainian", native: "Українська" },
    { code: "sv-SE", name: "Swedish", native: "Svenska" },
    { code: "no-NO", name: "Norwegian", native: "Norsk" },
    { code: "da-DK", name: "Danish", native: "Dansk" },
    { code: "fi-FI", name: "Finnish", native: "Suomi" },
    { code: "cs-CZ", name: "Czech", native: "Čeština" },
    { code: "el-GR", name: "Greek", native: "Ελληνικά" },
    { code: "he-IL", name: "Hebrew", native: "עברית" },
    { code: "ro-RO", name: "Romanian", native: "Română" },
    { code: "hu-HU", name: "Hungarian", native: "Magyar" },
    { code: "bg-BG", name: "Bulgarian", native: "Български" },
    { code: "hr-HR", name: "Croatian", native: "Hrvatski" },
    { code: "sr-RS", name: "Serbian", native: "Српски" },
    { code: "sk-SK", name: "Slovak", native: "Slovenčina" },
    { code: "sl-SI", name: "Slovenian", native: "Slovenščina" },
    { code: "et-EE", name: "Estonian", native: "Eesti" },
    { code: "lv-LV", name: "Latvian", native: "Latviešu" },
    { code: "lt-LT", name: "Lithuanian", native: "Lietuvių" },
    { code: "fa-IR", name: "Persian", native: "فارسی" },
    { code: "ur-PK", name: "Urdu", native: "اردو" },
    { code: "bn-IN", name: "Bengali", native: "বাংলা" },
    { code: "ta-IN", name: "Tamil", native: "தமிழ்" },
    { code: "te-IN", name: "Telugu", native: "తెలుగు" },
    { code: "mr-IN", name: "Marathi", native: "मराठी" },
    { code: "gu-IN", name: "Gujarati", native: "ગુજરાતી" },
    { code: "kn-IN", name: "Kannada", native: "ಕನ್ನಡ" },
    { code: "ml-IN", name: "Malayalam", native: "മലയാളം" },
    { code: "sw-KE", name: "Swahili", native: "Kiswahili" },
    { code: "af-ZA", name: "Afrikaans", native: "Afrikaans" }
];
